### ISSUE TITLE
Endpoint exist check

### ISSUE THREAD

**Issue by caseda** [athombv/node-homey-zwavedriver#4]
Now it is not possible to include the temperature sensors (DS18B20) to:

- Door/Window Sensor (FGK-101, FGK-10X);
- Universal Binary Sensor (FGBS-001);

These temperature sensor(s) will be added as endpoint(s), so need to be defined.
But this is impossible now because every endpoint noted in the JSON are being added.
And thus causes a fail in the inclusion when not attached to the Sensor's.

So there should be a check in the inclusion if the endpoint is there, if not, it will pass this endpoint and move on to the next step.

**Comment by kasteleman** [comment]
I also need this check for my Qubino devices. They have a TS connector to add temperature sensor. But also there are some that can use some sensors as input instead of a button. So i need a multi channel check. For example if there is a sensor connected only to the TS connector and no sensor at the input, then the tempsensor is the second endpont cq channel.

**Comment by caseda** [comment]
Kinda been fixed now. 

It does not crash anymore, but it will keep the the capability (null value) in the mobile card.
